library verilog;
use verilog.vl_types.all;
entity \_openmips\ is
    port(
        rst             : in     vl_logic;
        clk             : in     vl_logic;
        stallreq_from_if: in     vl_logic;
        rom_data_i      : in     vl_logic_vector(31 downto 0);
        int             : in     vl_logic_vector(5 downto 0);
        rom_addr_o      : out    vl_logic_vector(31 downto 0);
        rom_ce_o        : out    vl_logic;
        dwishbone_data_i: in     vl_logic_vector(31 downto 0);
        dwishbone_ack_i : in     vl_logic;
        dwishbone_addr_o: out    vl_logic_vector(31 downto 0);
        dwishbone_data_o: out    vl_logic_vector(31 downto 0);
        dwishbone_we_o  : out    vl_logic;
        dwishbone_sel_o : out    vl_logic_vector(3 downto 0);
        dwishbone_stb_o : out    vl_logic;
        dwishbone_cyc_o : out    vl_logic;
        timer_int       : out    vl_logic;
        regfile0        : out    vl_logic_vector(31 downto 0);
        regfile1        : out    vl_logic_vector(31 downto 0);
        regfile2        : out    vl_logic_vector(31 downto 0);
        regfile3        : out    vl_logic_vector(31 downto 0);
        regfile4        : out    vl_logic_vector(31 downto 0);
        regfile5        : out    vl_logic_vector(31 downto 0);
        regfile6        : out    vl_logic_vector(31 downto 0);
        regfile7        : out    vl_logic_vector(31 downto 0);
        regfile8        : out    vl_logic_vector(31 downto 0);
        regfile9        : out    vl_logic_vector(31 downto 0);
        regfile10       : out    vl_logic_vector(31 downto 0);
        regfile11       : out    vl_logic_vector(31 downto 0);
        regfile12       : out    vl_logic_vector(31 downto 0);
        regfile13       : out    vl_logic_vector(31 downto 0);
        regfile14       : out    vl_logic_vector(31 downto 0);
        regfile15       : out    vl_logic_vector(31 downto 0);
        regfile16       : out    vl_logic_vector(31 downto 0);
        regfile17       : out    vl_logic_vector(31 downto 0);
        regfile18       : out    vl_logic_vector(31 downto 0);
        regfile19       : out    vl_logic_vector(31 downto 0);
        regfile20       : out    vl_logic_vector(31 downto 0);
        regfile21       : out    vl_logic_vector(31 downto 0);
        regfile22       : out    vl_logic_vector(31 downto 0);
        regfile23       : out    vl_logic_vector(31 downto 0);
        regfile24       : out    vl_logic_vector(31 downto 0);
        regfile25       : out    vl_logic_vector(31 downto 0);
        regfile26       : out    vl_logic_vector(31 downto 0);
        regfile27       : out    vl_logic_vector(31 downto 0);
        regfile28       : out    vl_logic_vector(31 downto 0);
        regfile29       : out    vl_logic_vector(31 downto 0);
        regfile30       : out    vl_logic_vector(31 downto 0);
        regfile31       : out    vl_logic_vector(31 downto 0)
    );
end \_openmips\;
