######################################################################
#
# File name : openmips_min_sopc_post_tb.udo
# Created on: Sat Dec 17 16:45:36 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
