######################################################################
#
# File name : openmips_min_sopc_tb_simulate.do
# Created on: Sun Nov 20 16:28:01 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L dist_mem_gen_v8_0_10 -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.openmips_min_sopc_tb xil_defaultlib.glbl

do {openmips_min_sopc_tb_wave.do}

view wave
view structure
view signals

do {openmips_min_sopc_tb.udo}

run 10000ns
