######################################################################
#
# File name : openmips_min_sopc_tb_compile.do
# Created on: Sat Nov 19 14:59:17 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlib work
D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlib msim

D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlib msim/xil_defaultlib

D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vmap xil_defaultlib msim/xil_defaultlib

D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../" \
"../../../CPU54.srcs/sources_1/new/regfile.v" \
"../../../CPU54.srcs/sources_1/new/pc.v" \
"../../../CPU54.srcs/sources_1/new/MEM_WB.v" \
"../../../CPU54.srcs/sources_1/new/MEM.v" \
"../../../CPU54.srcs/sources_1/new/IF_ID.v" \
"../../../CPU54.srcs/sources_1/new/ID_EX.v" \
"../../../CPU54.srcs/sources_1/new/ID.v" \
"../../../CPU54.srcs/sources_1/new/HILO.v" \
"../../../CPU54.srcs/sources_1/new/EX_MEM.v" \
"../../../CPU54.srcs/sources_1/new/EX.v" \
"../../../CPU54.srcs/sources_1/new/DIV.v" \
"../../../CPU54.srcs/sources_1/new/CTRL.v" \
"../../../CPU54.srcs/sources_1/new/CP0.v" \
"../../../CPU54.srcs/sources_1/new/openmips.v" \
"../../../CPU54.srcs/sources_1/new/inst_rom.v" \
"../../../CPU54.srcs/sources_1/new/data_ram.v" \
"../../../CPU54.srcs/sources_1/new/openmips_min_sopc.v" \
"../../../CPU54.srcs/sim_1/new/openmips_min_sopc_tb.v" \


# compile glbl module
D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlog -work xil_defaultlib "glbl.v"

quit -force

