######################################################################
#
# File name : openmips_min_sopc_tb_wave.do
# Created on: Sun Nov 20 16:28:01 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
