######################################################################
#
# File name : openmips_min_sopc_post_tb_wave.do
# Created on: Sat Dec 17 23:27:48 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
