######################################################################
#
# File name : openmips_min_sopc_post_tb_compile.do
# Created on: Sat Dec 17 23:27:45 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlib work
D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlib msim

D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlib msim/dist_mem_gen_v8_0_10
D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlib msim/xil_defaultlib

D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10
D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vmap xil_defaultlib msim/xil_defaultlib

D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlog -64 -incr -work dist_mem_gen_v8_0_10  "+incdir+../../../" \
"../../../CPU54.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../" \
"../../../CPU54.ip_user_files/ip/imem/sim/imem.v" \
"../../../CPU54.srcs/sources_1/new/defines.v" \
"../../../CPU54.srcs/sources_1/new/regfile.v" \
"../../../CPU54.srcs/sources_1/new/pc.v" \
"../../../CPU54.srcs/sources_1/new/MEM_WB.v" \
"../../../CPU54.srcs/sources_1/new/MEM.v" \
"../../../CPU54.srcs/sources_1/new/IF_ID.v" \
"../../../CPU54.srcs/sources_1/new/ID_EX.v" \
"../../../CPU54.srcs/sources_1/new/ID.v" \
"../../../CPU54.srcs/sources_1/new/HILO.v" \
"../../../CPU54.srcs/sources_1/new/EX_MEM.v" \
"../../../CPU54.srcs/sources_1/new/EX.v" \
"../../../CPU54.srcs/sources_1/new/DIV.v" \
"../../../CPU54.srcs/sources_1/new/CTRL.v" \
"../../../CPU54.srcs/sources_1/new/CP0.v" \
"../../../CPU54.srcs/sources_1/new/openmips.v" \
"../../../CPU54.srcs/sources_1/new/inst_rom.v" \
"../../../CPU54.srcs/sources_1/new/data_ram.v" \
"../../../CPU54.srcs/sources_1/new/openmips_min_sopc.v" \
"../../../CPU54.srcs/sources_1/new/seg7x16.v" \
"../../../CPU54.srcs/sources_1/new/openmips_min_sopc_board.v" \
"../../../CPU54.srcs/sources_1/new/PIL.v" \
"../../../CPU54.srcs/sources_1/new/LLbit.v" \
"../../../CPU54.srcs/sources_1/new/wishbone_bus_if.v" \
"../../../CPU54.srcs/sources_1/new/openmips_min_sopc_post.v" \
"../../../CPU54.srcs/sources_1/new/_openmips.v" \
"../../../CPU54.srcs/sources_1/new/_regfile.v" \
"../../../CPU54.srcs/sim_1/new/openmips_min_sopc_tb.v" \
"../../../CPU54.srcs/sim_1/new/openmips_min_sopc_post_tb.v" \

# compile glbl module
D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlog -work xil_defaultlib "glbl.v"

quit -force

