######################################################################
#
# File name : openmips_min_sopc_tb_simulate.do
# Created on: Sat Nov 19 14:59:19 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.openmips_min_sopc_tb xil_defaultlib.glbl

do {openmips_min_sopc_tb_wave.do}

view wave
view structure
view signals

do {openmips_min_sopc_tb.udo}

run 10000ns
