######################################################################
#
# File name : openmips_min_sopc_tb_wave.do
# Created on: Fri Dec 09 16:49:44 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
