######################################################################
#
# File name : openmips_min_sopc_tb_wave.do
# Created on: Sat Nov 19 14:59:19 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
