######################################################################
#
# File name : openmips_min_sopc_post_tb_simulate.do
# Created on: Sat Dec 17 23:27:48 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L dist_mem_gen_v8_0_10 -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.openmips_min_sopc_post_tb xil_defaultlib.glbl

do {openmips_min_sopc_post_tb_wave.do}

view wave
view structure
view signals

do {openmips_min_sopc_post_tb.udo}

run 1000ns
