######################################################################
#
# File name : openmips_min_sopc_board.udo
# Created on: Fri Dec 09 16:29:16 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
