######################################################################
#
# File name : sccpu_pre_tb.udo
# Created on: Fri Aug 19 16:09:09 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
