######################################################################
#
# File name : sccpu_tb.udo
# Created on: Fri Aug 19 16:02:11 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
