######################################################################
#
# File name : sccpu_pre_tb_wave.do
# Created on: Fri Aug 19 23:05:14 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
