######################################################################
#
# File name : sccpu_pre_tb_simulate.do
# Created on: Fri Aug 19 23:05:14 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.sccpu_pre_tb xil_defaultlib.glbl

do {sccpu_pre_tb_wave.do}

view wave
view structure
view signals

do {sccpu_pre_tb.udo}

run 10000ns
