# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath D:/digital_logic/modelsim_10.4c/_modelsim/win32
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/digital_logic/project/CPU54/CPU54.cache/wt [current_project]
set_property parent.project_path D:/digital_logic/project/CPU54/CPU54.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property include_dirs D:/digital_logic/project/CPU54 [current_fileset]
add_files c:/Users/86183/Desktop/mips_54_mars_simulate_student_ForWeb.coe
add_files c:/Users/86183/Desktop/mips_54_mars_board_switch_student.coe
add_files c:/Users/86183/Desktop/mips_54_mars_simulate_student.coe
add_files -quiet D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/ip/imem/imem.dcp
set_property used_in_implementation false [get_files D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/ip/imem/imem.dcp]
read_verilog -library xil_defaultlib {
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/defines.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/divide_clk.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/regfile.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/pc.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/MEM_WB.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/MEM.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/IF_ID.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/ID_EX.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/ID.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/HILO.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/EX_MEM.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/EX.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/DIV.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/CTRL.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/CP0.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/seg7x16.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/PIL.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/CPU54.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/data_ram.v
  D:/digital_logic/project/CPU54/CPU54.srcs/sources_1/new/cpu.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/digital_logic/project/CPU54/CPU54.srcs/constrs_1/new/icf.xdc
set_property used_in_implementation false [get_files D:/digital_logic/project/CPU54/CPU54.srcs/constrs_1/new/icf.xdc]


synth_design -top cpu -part xc7a100tcsg324-1


write_checkpoint -force -noxdef cpu.dcp

catch { report_utilization -file cpu_utilization_synth.rpt -pb cpu_utilization_synth.pb }
