# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath D:/digital_logic/modelsim_10.4c/_modelsim/win32
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/desktop/MIPS_CPU/CPU54.cache/wt [current_project]
set_property parent.project_path D:/desktop/MIPS_CPU/CPU54.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property include_dirs D:/desktop/MIPS_CPU [current_fileset]
add_files d:/desktop/MIPS_CPU/CPU54.srcs/coe/mips_54_mars_simulate_student.coe
add_files d:/desktop/MIPS_CPU/CPU54.srcs/coe/eggTest.coe
add_files -quiet D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/ip/imem/imem.dcp
set_property used_in_implementation false [get_files D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/ip/imem/imem.dcp]
read_verilog -library xil_defaultlib {
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/defines.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/regfile.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/pc.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/MEM_WB.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/MEM.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/IF_ID.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/ID_EX.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/ID.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/HILO.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/EX_MEM.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/EX.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/DIV.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/CTRL.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/CP0.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/openmips.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/inst_rom.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/data_ram.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/openmips_min_sopc.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/seg7x16.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/openmips_min_sopc_board.v
  D:/desktop/MIPS_CPU/CPU54.srcs/sources_1/new/PIL.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/desktop/MIPS_CPU/CPU54.srcs/constrs_1/new/icf.xdc
set_property used_in_implementation false [get_files D:/desktop/MIPS_CPU/CPU54.srcs/constrs_1/new/icf.xdc]


synth_design -top openmips_min_sopc_board -part xc7a100tcsg324-1


write_checkpoint -force -noxdef openmips_min_sopc_board.dcp

catch { report_utilization -file openmips_min_sopc_board_utilization_synth.rpt -pb openmips_min_sopc_board_utilization_synth.pb }
