######################################################################
#
# File name : sccpu_tb_compile.do
# Created on: Sat Aug 20 13:51:04 +0800 2022
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlib work
D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlib msim

D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlib msim/xil_defaultlib

D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vmap xil_defaultlib msim/xil_defaultlib

D:\\digital_logic\\modelsim_10.4c\\_modelsim\\win32\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../" \
"sccpu_tb_time_synth.v" \
"../../../../CPU54.srcs/sources_1/new/divide_clk.v" \
"../../../../CPU54.srcs/sources_1/new/regfile.v" \
"../../../../CPU54.srcs/sources_1/new/pc.v" \
"../../../../CPU54.srcs/sources_1/new/MEM_WB.v" \
"../../../../CPU54.srcs/sources_1/new/MEM.v" \
"../../../../CPU54.srcs/sources_1/new/IF_ID.v" \
"../../../../CPU54.srcs/sources_1/new/ID_EX.v" \
"../../../../CPU54.srcs/sources_1/new/ID.v" \
"../../../../CPU54.srcs/sources_1/new/HILO.v" \
"../../../../CPU54.srcs/sources_1/new/EX_MEM.v" \
"../../../../CPU54.srcs/sources_1/new/EX.v" \
"../../../../CPU54.srcs/sources_1/new/DIV.v" \
"../../../../CPU54.srcs/sources_1/new/CTRL.v" \
"../../../../CPU54.srcs/sources_1/new/CP0.v" \
"../../../../CPU54.srcs/sources_1/new/CPU54.v" \
"../../../../CPU54.srcs/sources_1/new/data_ram.v" \
"../../../../CPU54.srcs/sources_1/new/sccpu.v" \
"../../../../CPU54.srcs/sim_1/new/sccpu_tb.v" \


quit -force

