######################################################################
#
# File name : sccpu_tb_simulate.do
# Created on: Sat Aug 20 13:51:45 +0800 2022
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vsim -voptargs="+acc" +transport_int_delays +pulse_r/0 +pulse_int_r/0 -L simprims_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.sccpu_tb xil_defaultlib.glbl

do {sccpu_tb_wave.do}

view wave
view structure
view signals

do {sccpu_tb.udo}

run 10000ns
