######################################################################
#
# File name : sccpu_tb.udo
# Created on: Sat Aug 20 10:54:20 +0800 2022
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
