######################################################################
#
# File name : sccpu_pre_tb.udo
# Created on: Sat Aug 20 10:47:49 +0800 2022
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
