######################################################################
#
# File name : sccpu_tb_wave.do
# Created on: Sat Aug 20 13:51:45 +0800 2022
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
