library verilog;
use verilog.vl_types.all;
entity \_regfile\ is
    port(
        clk             : in     vl_logic;
        rst             : in     vl_logic;
        write           : in     vl_logic;
        write_addr      : in     vl_logic_vector(4 downto 0);
        write_data      : in     vl_logic_vector(31 downto 0);
        ra              : in     vl_logic;
        addra           : in     vl_logic_vector(4 downto 0);
        dataa           : out    vl_logic_vector(31 downto 0);
        rb              : in     vl_logic;
        addrb           : in     vl_logic_vector(4 downto 0);
        datab           : out    vl_logic_vector(31 downto 0);
        regfile0        : out    vl_logic_vector(31 downto 0);
        regfile1        : out    vl_logic_vector(31 downto 0);
        regfile2        : out    vl_logic_vector(31 downto 0);
        regfile3        : out    vl_logic_vector(31 downto 0);
        regfile4        : out    vl_logic_vector(31 downto 0);
        regfile5        : out    vl_logic_vector(31 downto 0);
        regfile6        : out    vl_logic_vector(31 downto 0);
        regfile7        : out    vl_logic_vector(31 downto 0);
        regfile8        : out    vl_logic_vector(31 downto 0);
        regfile9        : out    vl_logic_vector(31 downto 0);
        regfile10       : out    vl_logic_vector(31 downto 0);
        regfile11       : out    vl_logic_vector(31 downto 0);
        regfile12       : out    vl_logic_vector(31 downto 0);
        regfile13       : out    vl_logic_vector(31 downto 0);
        regfile14       : out    vl_logic_vector(31 downto 0);
        regfile15       : out    vl_logic_vector(31 downto 0);
        regfile16       : out    vl_logic_vector(31 downto 0);
        regfile17       : out    vl_logic_vector(31 downto 0);
        regfile18       : out    vl_logic_vector(31 downto 0);
        regfile19       : out    vl_logic_vector(31 downto 0);
        regfile20       : out    vl_logic_vector(31 downto 0);
        regfile21       : out    vl_logic_vector(31 downto 0);
        regfile22       : out    vl_logic_vector(31 downto 0);
        regfile23       : out    vl_logic_vector(31 downto 0);
        regfile24       : out    vl_logic_vector(31 downto 0);
        regfile25       : out    vl_logic_vector(31 downto 0);
        regfile26       : out    vl_logic_vector(31 downto 0);
        regfile27       : out    vl_logic_vector(31 downto 0);
        regfile28       : out    vl_logic_vector(31 downto 0);
        regfile29       : out    vl_logic_vector(31 downto 0);
        regfile30       : out    vl_logic_vector(31 downto 0);
        regfile31       : out    vl_logic_vector(31 downto 0)
    );
end \_regfile\;
